package view;

import control.DriverControl;
import control.TaksiControl;
import control.PenggunaanControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Driver;
import model.Taksi;
import model.Penggunaan;
import table.TablePenggunaan;
import exception.InputanKosongException;
import java.awt.Dimension;
import session.AppSession;

public class PenggunaanView extends javax.swing.JFrame {
    
    private DriverControl driverControl;
    private TaksiControl taksiControl;
    private PenggunaanControl penggunaanControl;
    String action = null;
    List<Driver> listDriver;
    List<Taksi> listTaksi;
    int selectedId = 0;
    
    public PenggunaanView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        driverControl = new DriverControl();
        taksiControl = new TaksiControl();
        penggunaanControl = new PenggunaanControl();
        showPenggunaan();
        setDriverToDropdown();
        setTaksiToDropdown();
        String role = AppSession.getInstance().getRole();
        
        if(role.equalsIgnoreCase("Admin")){
            userPanel.setVisible(false);
            sidebarPanel.setPreferredSize(new Dimension(129, 645));
        }
    }
    
    public void setDriverToDropdown(){
        listDriver = driverControl.showListDriver();
        for(int i = 0; i < listDriver.size(); i++){
            driverDropdown.addItem(listDriver.get(i));
        }
    }
    
    public void setTaksiToDropdown(){
        listTaksi = taksiControl.showListTaksi();
        for(int i = 0; i < listTaksi.size(); i++){
            taksiDropdown.addItem(listTaksi.get(i));
        }
    }
    
    public void setComponent(boolean value){
        driverDropdown.setEnabled(value);
        taksiDropdown.setEnabled(value);
        penumpangInput.setEnabled(value);
        tarifInput.setEnabled(value);
        tanggalInput.setEnabled(value);
        layananInput.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        driverDropdown.setSelectedItem(ABORT);
        taksiDropdown.setSelectedItem(ABORT);
        penumpangInput.setText("");
        tarifInput.setText("");
        tanggalInput.setText("");
        layananInput.setText("");
        
        searchInput.setText("");
    }
    
    public void showPenggunaan(){
        tablePenggunaan.setModel(penggunaanControl.showPenggunaan(""));
    }
    
    public void inputanKosongException() throws InputanKosongException{
        if(driverDropdown.getSelectedIndex() == -1 || taksiDropdown.getSelectedIndex() == -1 || penumpangInput.getText().isEmpty()
            || tanggalInput.getText().isEmpty() || layananInput.getText().isEmpty() || tarifInput.getText().isEmpty()){
            throw new InputanKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        driverPanel = new javax.swing.JPanel();
        driverIcon = new javax.swing.JLabel();
        taxiPanel = new javax.swing.JPanel();
        taxiIcon = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        historyIcon = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        headerPanel5 = new javax.swing.JPanel();
        penggunaLabel7 = new javax.swing.JLabel();
        motoLabel5 = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        namaDriverPanel = new javax.swing.JLabel();
        tanggalInput = new javax.swing.JTextField();
        tanggalLabel = new javax.swing.JLabel();
        platLabel = new javax.swing.JLabel();
        taksiDropdown = new javax.swing.JComboBox<>();
        layananInput = new javax.swing.JTextField();
        layananLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenggunaan = new javax.swing.JTable();
        driverDropdown = new javax.swing.JComboBox<>();
        penumpangLabel = new javax.swing.JLabel();
        penumpangInput = new javax.swing.JTextField();
        tarifLabel = new javax.swing.JLabel();
        tarifInput = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(0, 51, 153));

        driverPanel.setBackground(new java.awt.Color(0, 51, 153));
        driverPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverPanelMouseClicked(evt);
            }
        });

        driverIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        driverIcon.setForeground(new java.awt.Color(255, 255, 255));
        driverIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Driver.png"))); // NOI18N
        driverIcon.setText("   Driver");
        driverIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        driverIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        driverIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout driverPanelLayout = new javax.swing.GroupLayout(driverPanel);
        driverPanel.setLayout(driverPanelLayout);
        driverPanelLayout.setHorizontalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        driverPanelLayout.setVerticalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        taxiPanel.setBackground(new java.awt.Color(0, 51, 153));
        taxiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taxiPanelMouseClicked(evt);
            }
        });

        taxiIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxiIcon.setForeground(new java.awt.Color(255, 255, 255));
        taxiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Taksi.png"))); // NOI18N
        taxiIcon.setText("   Taxi");
        taxiIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        taxiIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        taxiIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout taxiPanelLayout = new javax.swing.GroupLayout(taxiPanel);
        taxiPanel.setLayout(taxiPanelLayout);
        taxiPanelLayout.setHorizontalGroup(
            taxiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taxiPanelLayout.setVerticalGroup(
            taxiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taxiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        historyPanel.setBackground(new java.awt.Color(0, 0, 102));

        historyIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        historyIcon.setForeground(new java.awt.Color(255, 255, 255));
        historyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        historyIcon.setText("   History");
        historyIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        historyIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        historyIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoPanel.setBackground(new java.awt.Color(0, 51, 153));

        logoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(logoIcon)
                .addGap(20, 20, 20))
        );

        userPanel.setBackground(new java.awt.Color(0, 51, 153));
        userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPanelMouseClicked(evt);
            }
        });

        userIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userIcon.setForeground(new java.awt.Color(255, 255, 255));
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        userIcon.setText("   User");
        userIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        userIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        userIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutIcon.setForeground(new java.awt.Color(255, 255, 255));
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        logoutIcon.setText("Logout");
        logoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taxiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(driverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(logoutIcon)
                .addGap(43, 43, 43))
        );

        headerPanel5.setBackground(new java.awt.Color(204, 204, 255));

        penggunaLabel7.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        penggunaLabel7.setText("History");

        motoLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        motoLabel5.setForeground(new java.awt.Color(51, 51, 51));
        motoLabel5.setText("Taxi ala kadarnya Jogja");

        searchInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        searchBtn.setBackground(new java.awt.Color(0, 51, 153));
        searchBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        searchBtn.setBorder(null);
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanel5Layout = new javax.swing.GroupLayout(headerPanel5);
        headerPanel5.setLayout(headerPanel5Layout);
        headerPanel5Layout.setHorizontalGroup(
            headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motoLabel5)
                    .addComponent(penggunaLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        headerPanel5Layout.setVerticalGroup(
            headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel5Layout.createSequentialGroup()
                .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(penggunaLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motoLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaDriverPanel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        namaDriverPanel.setForeground(new java.awt.Color(51, 51, 51));
        namaDriverPanel.setText("Nama Driver");

        tanggalInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tanggalInput.setForeground(new java.awt.Color(102, 102, 102));
        tanggalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalInputActionPerformed(evt);
            }
        });

        tanggalLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tanggalLabel.setText("Tanggal");

        platLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        platLabel.setText("Plat Nomor");

        taksiDropdown.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        taksiDropdown.setForeground(new java.awt.Color(102, 102, 102));

        layananInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        layananInput.setForeground(new java.awt.Color(102, 102, 102));
        layananInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layananInputActionPerformed(evt);
            }
        });

        layananLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        layananLabel.setText("Layanan");

        tablePenggunaan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 12)); // NOI18N
        tablePenggunaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Driver", "Gender", "Merk", "Plat", "Tanggal", "Layanan", "No Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePenggunaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenggunaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenggunaan);

        driverDropdown.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        driverDropdown.setForeground(new java.awt.Color(102, 102, 102));

        penumpangLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        penumpangLabel.setText("Penumpang");

        penumpangInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        penumpangInput.setForeground(new java.awt.Color(102, 102, 102));
        penumpangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penumpangInputActionPerformed(evt);
            }
        });

        tarifLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tarifLabel.setText("Tarif");

        tarifInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tarifInput.setForeground(new java.awt.Color(102, 102, 102));
        tarifInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifInputActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(25, 135, 84));
        addBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        addBtn.setText("Tambah");
        addBtn.setBorder(null);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(241, 196, 15));
        editBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        editBtn.setText("Ubah");
        editBtn.setBorder(null);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(220, 53, 69));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(penumpangLabel)
                                .addComponent(penumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(platLabel)
                                .addComponent(taksiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaDriverPanel))
                            .addComponent(driverDropdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tanggalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tarifLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tarifInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(layananLabel))
                            .addComponent(layananInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(277, 277, 277))
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(namaDriverPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driverDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(platLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taksiDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(penumpangLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(penumpangInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(tarifLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarifInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tanggalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(layananLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layananInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addComponent(headerPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalInputActionPerformed

    private void layananInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layananInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layananInputActionPerformed

    private void penumpangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penumpangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penumpangInputActionPerformed

    private void tarifInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifInputActionPerformed

    private void driverPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverPanelMouseClicked
        DriverView dv = new DriverView("No");
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_driverPanelMouseClicked

    private void taxiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taxiPanelMouseClicked
        TaksiView tv = new TaksiView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_taxiPanelMouseClicked

    private void tablePenggunaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenggunaanMouseClicked
        int indexDriver = -1;
        int indexTaksi = -1;
        setEditDeleteBtn(true);

        setComponent(false);

        int clickedRow = tablePenggunaan.getSelectedRow();
        TableModel tableModel = tablePenggunaan.getModel();

        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString());
        penumpangInput.setText(tableModel.getValueAt(clickedRow, 2).toString());
        tarifInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        tanggalInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        layananInput.setText(tableModel.getValueAt(clickedRow, 5).toString());

        String id_driver = tableModel.getValueAt(clickedRow, 7).toString();
        for(Driver driver : listDriver){
            if(String.valueOf(driver.getId()).equals(id_driver)){
                indexDriver = listDriver.indexOf(driver);
            }
        }

        driverDropdown.setSelectedIndex(indexDriver);

        String id_taksi = tableModel.getValueAt(clickedRow, 8).toString();
        for(Taksi taksi : listTaksi){
            if(String.valueOf(taksi.getId()).equals(id_taksi)) {
                indexTaksi = listTaksi.indexOf(taksi);
            }
        }

        taksiDropdown.setSelectedIndex(indexTaksi);
    }//GEN-LAST:event_tablePenggunaanMouseClicked

    private void userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseClicked
        UserView tv = new UserView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_userPanelMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);

        try {
            TablePenggunaan p = penggunaanControl.showPenggunaan(searchInput.getText());

            if (p.getRowCount() == 0) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan","Konfirmasi",JOptionPane.DEFAULT_OPTION);

            }else{
                tablePenggunaan.setModel(p);

            }

            clearText();
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);

        clearText();
        searchInput.setText("");
        action = "Tambah";
        driverDropdown.setSelectedIndex(0);
        taksiDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
            try{
                penggunaanControl.deletePenggunaan(selectedId);
                clearText();
                showPenggunaan();
                setComponent(false);
                setEditDeleteBtn(false);
            } catch(Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;
            case 1:
            break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputanKosongException();
            String fasilitas = "";
            int selectedIndexD = driverDropdown.getSelectedIndex();
            Driver selectedDriver = listDriver.get(selectedIndexD);
                int selectedIndexT = taksiDropdown.getSelectedIndex();
                Taksi selectedTaksi = listTaksi.get(selectedIndexT);

                if(action.equals("Tambah")){
                    Penggunaan p = new Penggunaan(tanggalInput.getText(),
                        layananInput.getText(), penumpangInput.getText(), Integer.parseInt(tarifInput.getText()), selectedDriver, selectedTaksi);
                    penggunaanControl.insertPenggunaan(p);
                } else{
                    Penggunaan p = new Penggunaan(selectedId, tanggalInput.getText(),
                        layananInput.getText(), penumpangInput.getText(), Integer.parseInt(tarifInput.getText()), selectedDriver, selectedTaksi);
                    penggunaanControl.updatePenggunaan(p);
                }
                clearText();
                showPenggunaan();
                setComponent(false);

                setEditDeleteBtn(false);
        } catch(InputanKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void logoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconMouseClicked
        // TODO add your handling code here:
        LoginView lg = new LoginView();
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenggunaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenggunaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenggunaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenggunaanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenggunaanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<Driver> driverDropdown;
    private javax.swing.JLabel driverIcon;
    private javax.swing.JPanel driverPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel headerPanel5;
    private javax.swing.JLabel historyIcon;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField layananInput;
    private javax.swing.JLabel layananLabel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel motoLabel5;
    private javax.swing.JLabel namaDriverPanel;
    private javax.swing.JLabel penggunaLabel7;
    private javax.swing.JTextField penumpangInput;
    private javax.swing.JLabel penumpangLabel;
    private javax.swing.JLabel platLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tablePenggunaan;
    private javax.swing.JComboBox<Taksi> taksiDropdown;
    private javax.swing.JTextField tanggalInput;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField tarifInput;
    private javax.swing.JLabel tarifLabel;
    private javax.swing.JLabel taxiIcon;
    private javax.swing.JPanel taxiPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
