package view;

import control.TaksiControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Taksi;
import table.TableTaksi;
import exception.InputanKosongException;
import java.awt.Dimension;
import java.awt.Font;
import session.AppSession;

public class TaksiView extends javax.swing.JFrame {
    private TaksiControl taksiControl;
    String action = null;
    List<Taksi> listTaksi;
    int selectedId = 0;
    
    public TaksiView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        taksiControl = new TaksiControl();
        showTaksi();
        String role = AppSession.getInstance().getRole();
        
        if(role.equalsIgnoreCase("Admin")){
            userPanel.setVisible(false);
            sidebarPanel.setPreferredSize(new Dimension(129, 645));
        }
        
        tableTaxi.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    }
    
    public void setComponent(boolean value){
        idInput.setEnabled(value);
        platInput.setEnabled(value);
        merekInput.setEnabled(value);
        jenisInput.setEnabled(value);
        kapasitasInput.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        idInput.setText("");
        platInput.setText("");
        merekInput.setText("");
        jenisInput.setText("");
        kapasitasInput.setText("");
        
        searchInput.setText("");
    }
    
    public void showTaksi(){
        tableTaxi.setModel(taksiControl.showTaksiBySearch(""));
    }
    
    public void inputanKosongException() throws InputanKosongException{
        if(platInput.getText().isEmpty() || merekInput.getText().isEmpty() || jenisInput.getText().isEmpty() || kapasitasInput.getText().isEmpty()){
            throw new InputanKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel5 = new javax.swing.JPanel();
        penggunaLabel7 = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        motoLabel6 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        driverPanel = new javax.swing.JPanel();
        driverIcon = new javax.swing.JLabel();
        taxiPanel = new javax.swing.JPanel();
        taxiIcon = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        historyIcon = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        jenisInput = new javax.swing.JTextField();
        jenisLabel = new javax.swing.JLabel();
        platLabel = new javax.swing.JLabel();
        platInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTaxi = new javax.swing.JTable();
        kapasitasLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        merekLabel = new javax.swing.JLabel();
        merekInput = new javax.swing.JTextField();
        kapasitasInput = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel5.setBackground(new java.awt.Color(204, 204, 255));

        penggunaLabel7.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        penggunaLabel7.setText("Taxi");

        searchInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        searchBtn.setBackground(new java.awt.Color(0, 51, 153));
        searchBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        searchBtn.setBorder(null);
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        motoLabel6.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        motoLabel6.setForeground(new java.awt.Color(51, 51, 51));
        motoLabel6.setText("Taxi ala kadarnya Jogja");

        javax.swing.GroupLayout headerPanel5Layout = new javax.swing.GroupLayout(headerPanel5);
        headerPanel5.setLayout(headerPanel5Layout);
        headerPanel5Layout.setHorizontalGroup(
            headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motoLabel6)
                    .addComponent(penggunaLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        headerPanel5Layout.setVerticalGroup(
            headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel5Layout.createSequentialGroup()
                .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(penggunaLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motoLabel6))
                    .addGroup(headerPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(headerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sidebarPanel.setBackground(new java.awt.Color(0, 51, 153));

        driverPanel.setBackground(new java.awt.Color(0, 51, 153));
        driverPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverPanelMouseClicked(evt);
            }
        });

        driverIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        driverIcon.setForeground(new java.awt.Color(255, 255, 255));
        driverIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Driver.png"))); // NOI18N
        driverIcon.setText("   Driver");
        driverIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        driverIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        driverIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout driverPanelLayout = new javax.swing.GroupLayout(driverPanel);
        driverPanel.setLayout(driverPanelLayout);
        driverPanelLayout.setHorizontalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        driverPanelLayout.setVerticalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        taxiPanel.setBackground(new java.awt.Color(0, 0, 102));
        taxiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taxiPanelMouseClicked(evt);
            }
        });

        taxiIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxiIcon.setForeground(new java.awt.Color(255, 255, 255));
        taxiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Taksi.png"))); // NOI18N
        taxiIcon.setText("   Taxi");
        taxiIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        taxiIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        taxiIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout taxiPanelLayout = new javax.swing.GroupLayout(taxiPanel);
        taxiPanel.setLayout(taxiPanelLayout);
        taxiPanelLayout.setHorizontalGroup(
            taxiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taxiPanelLayout.setVerticalGroup(
            taxiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taxiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        historyPanel.setBackground(new java.awt.Color(0, 51, 153));
        historyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyPanelMouseClicked(evt);
            }
        });

        historyIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        historyIcon.setForeground(new java.awt.Color(255, 255, 255));
        historyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        historyIcon.setText("   History");
        historyIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        historyIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        historyIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoPanel.setBackground(new java.awt.Color(0, 51, 153));

        logoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(logoIcon)
                .addGap(20, 20, 20))
        );

        userPanel.setBackground(new java.awt.Color(0, 51, 153));
        userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPanelMouseClicked(evt);
            }
        });

        userIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userIcon.setForeground(new java.awt.Color(255, 255, 255));
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        userIcon.setText("   User");
        userIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        userIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        userIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutIcon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutIcon.setForeground(new java.awt.Color(255, 255, 255));
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        logoutIcon.setText("Logout");
        logoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taxiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(driverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(logoutIcon)
                .addGap(56, 56, 56))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        idLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(51, 51, 51));
        idLabel.setText("ID Taxi");

        jenisInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jenisInput.setForeground(new java.awt.Color(102, 102, 102));
        jenisInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisInputActionPerformed(evt);
            }
        });

        jenisLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jenisLabel.setText("Jenis");

        platLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        platLabel.setText("Plat Nomor");

        platInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        platInput.setForeground(new java.awt.Color(102, 102, 102));
        platInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platInputActionPerformed(evt);
            }
        });

        tableTaxi.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 12)); // NOI18N
        tableTaxi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Driver", "Gender", "Merk", "Plat", "Tanggal", "Layanan", "No Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTaxi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTaxiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTaxi);

        kapasitasLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kapasitasLabel.setText("Kapasitas Penumpang");

        idInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        idInput.setForeground(new java.awt.Color(102, 102, 102));
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        merekLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        merekLabel.setText("Merek");

        merekInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        merekInput.setForeground(new java.awt.Color(102, 102, 102));
        merekInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekInputActionPerformed(evt);
            }
        });

        kapasitasInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kapasitasInput.setForeground(new java.awt.Color(102, 102, 102));
        kapasitasInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapasitasInputActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(25, 135, 84));
        addBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        addBtn.setText("Tambah");
        addBtn.setBorder(null);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(241, 196, 15));
        editBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        editBtn.setText("Ubah");
        editBtn.setBorder(null);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(220, 53, 69));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(kapasitasInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(platLabel)
                            .addComponent(idLabel)
                            .addComponent(platInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(merekLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(merekInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kapasitasLabel)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(platLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(merekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(merekInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jenisLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(kapasitasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kapasitasInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisInputActionPerformed

    private void platInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void merekInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merekInputActionPerformed

    private void kapasitasInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapasitasInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapasitasInputActionPerformed

    private void taxiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taxiPanelMouseClicked
        
    }//GEN-LAST:event_taxiPanelMouseClicked

    private void driverPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverPanelMouseClicked
        DriverView dv = new DriverView("No");
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_driverPanelMouseClicked

    private void tableTaxiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTaxiMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);

        int clickedRow = tableTaxi.getSelectedRow();
        TableModel tableModel = tableTaxi.getModel();

        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        idInput.setText(tableModel.getValueAt(clickedRow, 0).toString());
        platInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        merekInput.setText(tableModel.getValueAt(clickedRow, 2).toString());
        jenisInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        kapasitasInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
    }//GEN-LAST:event_tableTaxiMouseClicked

    private void historyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyPanelMouseClicked
        PenggunaanView pv = new PenggunaanView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_historyPanelMouseClicked

    private void userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseClicked
        UserView tv = new UserView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_userPanelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        
        clearText();
        searchInput.setText("");
        action = "Tambah";
        
        idInput.setEnabled(false);
        int generatedId = taksiControl.generateId();
        String generatedIdString = String.valueOf(generatedId);
        idInput.setText(generatedIdString);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        action = "Ubah";
        idInput.setEnabled(false);
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menghapus data ? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (getAnswer == JOptionPane.YES_OPTION) {
            try {
                taksiControl.deleteTaksi(selectedId);
                clearText();
                showTaksi();
                setComponent(false);
                setEditDeleteBtn(false);
                
                JOptionPane.showMessageDialog(null, "Data Taksi berhasil dihapus!");
            } catch (Exception e) {
                System.out.println("Error : "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data Taksi tidak jadi dihapus!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);

        try {
            TableTaksi td = taksiControl.showTaksiBySearch(searchInput.getText());

            if (td.getRowCount() == 0) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan","Konfirmasi",JOptionPane.DEFAULT_OPTION);
            } else{
                tableTaxi.setModel(td);
            }

            clearText();
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputanKosongException();
            if(action.equals("Tambah")) {
                Taksi t = new Taksi(Integer.parseInt(idInput.getText()), platInput.getText(), merekInput.getText(), jenisInput.getText(), Integer.parseInt(kapasitasInput.getText()));
                taksiControl.insertTaksi(t);
            } else {
                Taksi t = new Taksi(selectedId, platInput.getText(), merekInput.getText(), jenisInput.getText(), Integer.parseInt(kapasitasInput.getText()));
                taksiControl.updateTaksi(t);
            }
            clearText();
            showTaksi();
            setComponent(false);
            setEditDeleteBtn(false);
        } catch(InputanKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void logoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutIconMouseClicked
        // TODO add your handling code here:
        LoginView lg = new LoginView();
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel driverIcon;
    private javax.swing.JPanel driverPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel headerPanel5;
    private javax.swing.JLabel historyIcon;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jenisInput;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField kapasitasInput;
    private javax.swing.JLabel kapasitasLabel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JTextField merekInput;
    private javax.swing.JLabel merekLabel;
    private javax.swing.JLabel motoLabel6;
    private javax.swing.JLabel penggunaLabel7;
    private javax.swing.JTextField platInput;
    private javax.swing.JLabel platLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tableTaxi;
    private javax.swing.JLabel taxiIcon;
    private javax.swing.JPanel taxiPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
